- name: Hello World Sample
  hosts: all
  gather_facts: false
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! Now pausing job! Feel free to poke around inside the job's pod."
    - name: Pause so I can inspect the job pod
      pause:
        minutes: 10
    - name: Goodbye Message
      debug:
        msg: "Pause done! Goodbye!"
#ansible.windows.win_shell: 'Write-Output "Hello from $env:COMPUTERNAME"'
